#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
	selected=$(find ~/www /opt/sources -mindepth 1 -maxdepth 1 -type d 2>/dev/null | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi


session_name=$(basename "$selected" | tr . _)

if [[ -z $ZELLIJ ]]; then
	cd $selected
  
	zellij attach $session_name -c
	exit 0
fi

zellij action new-pane

zellij action write-chars "cd $selected" && zellij action write 10
